// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: statistics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOrderStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderStatisticsRequest) Reset() {
	*x = UserOrderStatisticsRequest{}
	mi := &file_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderStatisticsRequest) ProtoMessage() {}

func (x *UserOrderStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserOrderStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *UserOrderStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserOrderStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderCount    int32                  `protobuf:"varint,1,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	PeakOrderTime string                 `protobuf:"bytes,2,opt,name=peak_order_time,json=peakOrderTime,proto3" json:"peak_order_time,omitempty"` // e.g., "14:00-15:00"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderStatisticsResponse) Reset() {
	*x = UserOrderStatisticsResponse{}
	mi := &file_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderStatisticsResponse) ProtoMessage() {}

func (x *UserOrderStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserOrderStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *UserOrderStatisticsResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *UserOrderStatisticsResponse) GetPeakOrderTime() string {
	if x != nil {
		return x.PeakOrderTime
	}
	return ""
}

type UserStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatisticsRequest) Reset() {
	*x = UserStatisticsRequest{}
	mi := &file_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsRequest) ProtoMessage() {}

func (x *UserStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsRequest.ProtoReflect.Descriptor instead.
func (*UserStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *UserStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserStatisticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers     int32                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	UserOrderCount int32                  `protobuf:"varint,2,opt,name=user_order_count,json=userOrderCount,proto3" json:"user_order_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserStatisticsResponse) Reset() {
	*x = UserStatisticsResponse{}
	mi := &file_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsResponse) ProtoMessage() {}

func (x *UserStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *UserStatisticsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *UserStatisticsResponse) GetUserOrderCount() int32 {
	if x != nil {
		return x.UserOrderCount
	}
	return 0
}

// NATS events
type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "created", "updated", "deleted"
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *OrderEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *OrderEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type InventoryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "created", "updated", "deleted"
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryEvent) Reset() {
	*x = InventoryEvent{}
	mi := &file_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryEvent) ProtoMessage() {}

func (x *InventoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryEvent.ProtoReflect.Descriptor instead.
func (*InventoryEvent) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InventoryEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_statistics_proto protoreflect.FileDescriptor

const file_statistics_proto_rawDesc = "" +
	"\n" +
	"\x10statistics.proto\x12\n" +
	"statistics\"5\n" +
	"\x1aUserOrderStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"f\n" +
	"\x1bUserOrderStatisticsResponse\x12\x1f\n" +
	"\vorder_count\x18\x01 \x01(\x05R\n" +
	"orderCount\x12&\n" +
	"\x0fpeak_order_time\x18\x02 \x01(\tR\rpeakOrderTime\"0\n" +
	"\x15UserStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"c\n" +
	"\x16UserStatisticsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x12(\n" +
	"\x10user_order_count\x18\x02 \x01(\x05R\x0euserOrderCount\"k\n" +
	"\n" +
	"OrderEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"V\n" +
	"\x0eInventoryEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\xdb\x01\n" +
	"\x11StatisticsService\x12j\n" +
	"\x17GetUserOrdersStatistics\x12&.statistics.UserOrderStatisticsRequest\x1a'.statistics.UserOrderStatisticsResponse\x12Z\n" +
	"\x11GetUserStatistics\x12!.statistics.UserStatisticsRequest\x1a\".statistics.UserStatisticsResponseB!Z\x1fAssignment1_AdletMusabaev/protob\x06proto3"

var (
	file_statistics_proto_rawDescOnce sync.Once
	file_statistics_proto_rawDescData []byte
)

func file_statistics_proto_rawDescGZIP() []byte {
	file_statistics_proto_rawDescOnce.Do(func() {
		file_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_proto_rawDesc), len(file_statistics_proto_rawDesc)))
	})
	return file_statistics_proto_rawDescData
}

var file_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_statistics_proto_goTypes = []any{
	(*UserOrderStatisticsRequest)(nil),  // 0: statistics.UserOrderStatisticsRequest
	(*UserOrderStatisticsResponse)(nil), // 1: statistics.UserOrderStatisticsResponse
	(*UserStatisticsRequest)(nil),       // 2: statistics.UserStatisticsRequest
	(*UserStatisticsResponse)(nil),      // 3: statistics.UserStatisticsResponse
	(*OrderEvent)(nil),                  // 4: statistics.OrderEvent
	(*InventoryEvent)(nil),              // 5: statistics.InventoryEvent
}
var file_statistics_proto_depIdxs = []int32{
	0, // 0: statistics.StatisticsService.GetUserOrdersStatistics:input_type -> statistics.UserOrderStatisticsRequest
	2, // 1: statistics.StatisticsService.GetUserStatistics:input_type -> statistics.UserStatisticsRequest
	1, // 2: statistics.StatisticsService.GetUserOrdersStatistics:output_type -> statistics.UserOrderStatisticsResponse
	3, // 3: statistics.StatisticsService.GetUserStatistics:output_type -> statistics.UserStatisticsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_statistics_proto_init() }
func file_statistics_proto_init() {
	if File_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_proto_rawDesc), len(file_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_proto_depIdxs,
		MessageInfos:      file_statistics_proto_msgTypes,
	}.Build()
	File_statistics_proto = out.File
	file_statistics_proto_goTypes = nil
	file_statistics_proto_depIdxs = nil
}
